### ISSUE TITLE
steamless failed to unpack file using your v3.1.0.3

### ISSUE THREAD

**Issue by Team-LiL** [atom0s/Steamless#100]
DaveTheDiver.exe  failed to to unpack exe steamless drm stub
game was released  28 Jun, 2023 on steam page
maybe its a new variant library needed

**Comment by Team-LiL** [comment]
https://www.mirrored.to/files/ZBK1DO6R/DaveTheDiver_exe.rar_links
here is the exe in case you want to examine it

**Comment by atom0s** [comment]
While this file is packed with SteamStub, it is also packed with Themida/WinLicense. However, they have applied Themida/WinLicense after they had already packed it with SteamStub, meaning you will have to unpack the file from that layer first before SteamStub can be removed.

This is not something Steamless will handle/do.
