### ISSUE TITLE
ARK: Survival Ascended fails on attempting to remove Steam DRM

### ISSUE THREAD

**Issue by Mika-Kyubi** [atom0s/Steamless#106]
ARK: Survival Ascended will not decrypt.  By default the game is located on C:\Program Files (x86)\Steam\steamapps\common\ARK Survival Ascended\ShooterGame\Binaries\Win64.  I am uncertain if I am missing something critical.

Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎12/‎2023
OS build	19045.3693
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Steam Version:  1700160213
Steam Client Build Date:  Thu, Nov 16 1:25 PM UTC -08:00
Steam Web Build Date:  Thu, Nov 16 1:06 PM UTC -08:00
Steam API Version:  SteamClient021

![image](https://github.com/atom0s/Steamless/assets/87213906/e6df5908-19b8-4199-9298-525e41d55850)

**Comment by atom0s** [comment]
In order for me to check if there is a problem with Steamless, you will need to upload the .exe file(s) that the game uses somewhere and link them here.

**Comment by Mika-Kyubi** [comment]
https://www.dropbox.com/scl/fi/bndx4flqz9r2002ylee41/ArkAscended.exe?rlkey=btgw3jgfv2worc0s92cor0oab&dl=0

**Comment by Mika-Kyubi** [comment]
If there is any other help that I can give, I shall of course immediately endeavor to do so.

**Comment by atom0s** [comment]
This file is not packed with SteamStub.

**Comment by Mika-Kyubi** [comment]
Many thanks for that information, I shall proceed from there.
