### ISSUE TITLE
Category: Question / Help  - Can't unpack a x64 game [NOT A BUG]

### ISSUE THREAD

**Issue by ItsTheLya** [atom0s/Steamless#110]
Hello, I'm new to modding and wanted to get myself an AES key for Pacific Drive, to mod the game. I've tried following this guide: https://github.com/Cracko298/UE4-AES-Key-Extracting-Guide ; however everytime I try to remove DRM from the Shipping File (PenDriverPro-Win64-Shipping.exe), the shipping file for Pacific Drive, I get:

[ExamplePlugin] ExamplePlugin was asked to check if it can process a file!
[Steamless] Failed to unpack file

Any chance for help? I'm not extracting using Steamless straight from the zip file. its on the same disk as the game. Here's a short clip of the issue:

https://github.com/atom0s/Steamless/assets/81299523/fa605558-bae4-4f79-bdd4-055fe140f212

**Comment by atom0s** [comment]
Hello, can you please upload the game exe somewhere and link it here? I can take a look to see if there is an issue with this title.

**Comment by ItsTheLya** [comment]
Yes, of course. Here's the shipping manifest on a google drive:
https://drive.google.com/file/d/12W4oYBoSsxy_bwg_K_zcBlQmYq-Y7a_5/view?usp=sharing

**Comment by atom0s** [comment]
That file is not packed with SteamStub. I also just noticed; the video you uploaded shows that you have an old version of Steamless. You should update to the latest version. The newest version will inform you of this automatically now instead of just having the old somewhat useless error message.

**Comment by ItsTheLya** [comment]
Okay, updated it now. Since its not packed with SteamStub, is it still possible to remove the DRM with Steamless, or not really?

**Comment by atom0s** [comment]
Steamless only removes the SteamStub DRM layer. It will not (and will never) remove any other layer or kind of DRM. For example, this game also uses the SteamWorks API (steam_api64.dll) which this project will never assist with removing. If you are looking to remove other forms of DRM, then I will not assist with that.

**Comment by ItsTheLya** [comment]
Oh okay, thanks for the answer!
