### ISSUE TITLE
[Request] List of games that work with Steamless

### ISSUE THREAD

**Issue by st1vms** [atom0s/Steamless#111]
Is there any mantained list of games that have been successfully cracked using Steamless?

It would be cool if there could be a list where people could put the names of games that they could crack, as a reference.

**Comment by Klemci** [comment]
Games are not cracked here, understand better the project.

**Comment by atom0s** [comment]
Steamless is not for 'cracking' games. And no, a list like this is not something I plan to ever make or maintain.
