### ISSUE TITLE
v3.1.0.5, reapply all (over older release)

### ISSUE THREAD

**Issue by Klemci** [atom0s/Steamless#112]
Heloo,

is it recommended to reapply Steamless to each porecedently apllied EXE (using origina, yes) using latest version ? Using CLI can batch process in subfolders, tho ?

I used 3.1.0.3 previously !

If yes, what would be different with "new" _AES buffer size_... ? Globally !

//

Is there a next release in the work or v3.1.0.5 can be considered fully functionnal ad should not receive "bugfixes" or "enhancements" ?

**Comment by atom0s** [comment]
If the games you have unpacked in the past already work, then there shouldn't be any need to unpack them again. The newest version of Steamless fixes a bug that was causing some games to unpack incorrectly, but it does not affect every game or version of Steamless.
