### ISSUE TITLE
Steamless and Content Warning

### ISSUE THREAD

**Issue by ghost** [atom0s/Steamless#115]
I can't for the life of me figure out how to use Steamless. I do own Content Warning from April 1st. I copy and pasted the files onto my laptop that can't get steam for some reason. It gives me some error messages I have no idea how to fix. I know I did something wrong, but I can't figure out what to do. [Image](https://attachment.outlook.live.net/owa/MSA%3Areversanator%40outlook.com/service.svc/s/GetAttachmentThumbnail?id=AQMkADAwATM3ZmYAZS1kOTdhLWYyZjYtMDACLTAwCgBGAAADzdBhaFMNv0SQpSWz0cZMQQcAoeTyy%2BlhWkGknedmRnjRnAAAAgEJAAAAoeTyy%2BlhWkGknedmRnjRnAAHTNC1OgAAAAESABAA53rgCTHF4kqvTFRTx9VX0g%3D%3D&thumbnailType=2&isc=1&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkU1RDJGMEY4REE5M0I2NzA5QzQzQTlFOEE2MTQzQzAzRDYyRjlBODAiLCJ0eXAiOiJKV1QiLCJ4NXQiOiI1ZEx3LU5xVHRuQ2NRNm5vcGhROEE5WXZtb0EifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2subGl2ZS5jb20iLCJ1YyI6Ijk1YTE1YmU0ZGQyMTQ1ODY4YzMwZjZiYzM0YjJkMjM4IiwidmVyIjoiRXhjaGFuZ2UuQ2FsbGJhY2suVjEiLCJhcHBjdHhzZW5kZXIiOiJPd2FEb3dubG9hZEA4NGRmOWU3Zi1lOWY2LTQwYWYtYjQzNS1hYWFhYWFhYWFhYWEiLCJpc3NyaW5nIjoiV1ciLCJhcHBjdHgiOiJ7XCJtc2V4Y2hwcm90XCI6XCJvd2FcIixcInB1aWRcIjpcIjk4NTE1NzQ3NzI2NjE2NlwiLFwic2NvcGVcIjpcIk93YURvd25sb2FkXCIsXCJvaWRcIjpcIjAwMDM3ZmZlLWQ5N2EtZjJmNi0wMDAwLTAwMDAwMDAwMDAwMFwiLFwicHJpbWFyeXNpZFwiOlwiUy0xLTI4MjctMjI5Mzc0LTM2NDg3MTM0NjJcIn0iLCJuYmYiOjE3MTUwOTg5NjUsImV4cCI6MTcxNTA5OTU2NSwiaXNzIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwQDg0ZGY5ZTdmLWU5ZjYtNDBhZi1iNDM1LWFhYWFhYWFhYWFhYSIsImF1ZCI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9hdHRhY2htZW50Lm91dGxvb2subGl2ZS5uZXRAODRkZjllN2YtZTlmNi00MGFmLWI0MzUtYWFhYWFhYWFhYWFhIiwiaGFwcCI6Im93YSJ9.bKyIVG4-0zqftgCSFP1ZzMKmIJEBTLXWcZ3RYQF_eJK49z1E657fLlUZ_1xjo3CKymaB3srpw7eYgSTf_TdFFgcXN9uG38pc4VNzfjyjyUsh7RaJSJ1B9Yf0BADfqSxAjpNNM9K6kmdAYXriTwG8k-xIevtKOhvHIATDRkRlu75ChnmdIFKk7LXzt2fZJ0ICokcLvhptKjTeIAB-lQ-EO4LyR_CzjdIOmnIsXi3NBucv84jceMjEi_cJar43M-1zLa26FRprROnmzynrcm6PuHPDLZbTV3HaTwbfmuYh2ZY8QHAjqUO7y9qCI8Fzcla6YtCkrid701p9TllGshpn9w&X-OWA-CANARY=bdvoV3QGqx0AAAAAAAAAAMABqfixbtwYlzIx4T-FNGjlx_0hvHxW_AbNrQfZLnZo4RVObpMVQSo.&owa=outlook.live.com&scriptVer=20240419007.32&clientId=F50D09D9D5DC46A7A653378B5C7DC8E5&animation=true)

**Comment by atom0s** [comment]
What does the error message say? The link to that image does not work.

**Comment by ghost** [comment]
[Steamless]
[Steamless] This file does not appear to be packed with SteamStub!
[Steamless] File missing expected '.bind' section!
[Steamless]
[Steamless] Failed to unpack file

**Comment by atom0s** [comment]
Did you actually read the message..? The game does not use SteamStub therefore Steamless will not work with it.

**Comment by ghost** [comment]
My bad I just haven't been able to find out what to do. My bad sorry for wasting your time adios forever.
