### ISSUE TITLE
REHDHook, fixed

### ISSUE THREAD

**Issue by Klemci** [atom0s/Steamless#117]
hello,

i written long ago on moddingboard, anyway i found the solution...

... as REHDHook can't quit the game (black screen that needs logoff, not even task manager can fix it), then if the d3d9 DLL of the filters switcher mod (well known on pcgwiki, oh and i just seen fusion fix now too listed) is applied it fixed quit behavior of REHDHook, but the map and inventory are blackscreen, NO more, **infact if only the dll but not the ini nor shaders folder is applied, it's all good.**

JFYI.

https://www.pcgamingwiki.com/wiki/Resident_Evil_HD_Remaster#Post-processing

**Comment by atom0s** [comment]
This repository is not the place to discuss things like that. It has nothing to do with my REHDHook project.
