### ISSUE TITLE
Failed to unpack file Dungeonborne

### ISSUE THREAD

**Issue by Zefzz** [atom0s/Steamless#119]
[Steamless] This file does not appear to be packed with SteamStub!
[Steamless] File missing expected '.bind' section!

The game is in x64 and was made on UE4.

Heres the executable
https://drive.google.com/drive/folders/1aBs105Wvr0KYbivrw5tSJ1a3CtEicGaz?usp=sharing

**Comment by atom0s** [comment]
This game is not packed with SteamStub as the error states.
