### ISSUE TITLE
regression 3.1.0.5

### ISSUE THREAD

**Issue by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [atom0s/Steamless#123]
latest version 3.1.05 fails to unpack a 201{2/3} game with error:
```
Caught unhandled exception trying to unpack file.
Exception:
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

while previous version 3.1.03 successfully removed the drm.
the executable is packed with steam drm 2.1

**Comment by atom0s** [comment]
I would need the exe to be able to see what may be happening.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
[steamstub21.zip](https://github.com/user-attachments/files/16823500/steamstub21.zip)

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
> I would need the exe to be able to see what may be happening.

[steamstub21.zip](https://github.com/user-attachments/files/16823501/steamstub21.zip)

**Comment by YoteZip** [comment]
I can confirm that I got this same error with 3.1.0.5 and not with 3.1.0.3. My file was also SteamStub 2.1. The EXE is from Mirror's Edge, sha1 `9538dd552d8acdc5498e7b37a59ea5c434a2fb08` - this is the executable Steam serves right now. Let me know if you need a copy.

**Comment by atom0s** [comment]
This is the same issue that is reported here: https://github.com/atom0s/Steamless/issues/113

Tracking of this issue will continue there instead.
