### ISSUE TITLE
Not unpacking for exe after applying patch

### ISSUE THREAD

**Issue by DifficultyEnjoyer** [atom0s/Steamless#124]
So recently I downloaded dragon ball xenoverse 2 from fitgirl,the version 1.22.00

<piracy link removed>

which was working fine,then i downloaded the 1.22.02 patch from here

<piracy link removed>

applied the patch and the game just started to give me the 3:0000065432 error
![Screenshot (975)](https://github.com/user-attachments/assets/9f4b8aae-a5a3-4ed1-a8f2-75be698ecee0)

i then tried to use steamless on the exe file,but it just would not unpack,even after activating the experimental features

![Screenshot (976)](https://github.com/user-attachments/assets/a139869e-c9cd-4a93-ac7f-0f6c0b6ac892)

**Comment by atom0s** [comment]
I do not assist with, condone or support piracy.
