### ISSUE TITLE
clerefication: "piracy" term

### ISSUE THREAD

**Issue by axet** [atom0s/Steamless#125]
Hello!

Your readme states you will never support piracy. Can you clarify the term "piracy"?

I assume piracy referring to pirates - people who kill, rob and enslave other people?

But if you are using this term to describe people who sharing software for free you are miss using this term. Since clearly people who is share software for free are not pirates but "Robinhoods". And real pirates here is who saying: sharing is bad, it is OUR property. Clearly "pirates" are guys who claiming software belong to them - "right holders". 

Replacing term "piracy" with "I will not fight digital slavery by any means", would make much more sense.

**Comment by atom0s** [comment]
Go play in traffic.
