### ISSUE TITLE
Failed to unpack file.

### ISSUE THREAD

**Issue by abizeyshn** [atom0s/Steamless#127]
I tried to unpack the game file «The Casting of Frank Stone», but it gave me the error “Failed to unpack file.” and once the following error appeared in the logs: “This file does not appear to be packed with SteamStub!” and "File missing expected '.bind' section!".

Although there are no problems with other games.

![error](https://github.com/user-attachments/assets/5457241d-e716-4aef-9206-ef1af821f66a)

**Comment by atom0s** [comment]
As the message states, the file does not appear to be packed with SteamStub as it does not have the trademark `.bind` section present in the file. There is nothing for Steamless to do.
