### ISSUE TITLE
Issue with Dead Island Riptide

### ISSUE THREAD

**Issue by Chisanx** [atom0s/Steamless#137]
Hello atom0s,

When I try to unpack DeadIslandGame_x86_rwdi.exe, Steamless throws the following error:

<img width="646" alt="Capture" src="https://github.com/user-attachments/assets/7c14b419-ff34-4e0f-a9d7-1d59492d4403" />

Game in case is the Dead Island Riptide (2013). I can provide the executable if needed.

Steamless version: 3.1.0.5, default options selected
System: Windows 10 22H2, x64

**Comment by Chisanx** [comment]
Here's the .exe files.
[DeadIslandGame_x86_rwdi.zip](https://github.com/user-attachments/files/18269184/DeadIslandGame_x86_rwdi.zip)

**Comment by atom0s** [comment]
Hello, this is a currently known issue with the current version of the 2.1 unpacker plugin. You can try rolling back to an older version of Steamless and see if it works again for the time being.

**Comment by Chisanx** [comment]
Rolling back to ver. 3.1.0.0 fixes the problem. Thanks!
