### ISSUE TITLE
[Question/Request] Command-line support?

### ISSUE THREAD

**Issue by Kiefy** [atom0s/Steamless#14]
Is it possible to operate entirely within command-line/batch script, like `Steamless.exe "%1"`?

If not, could I please request this feature.

**Comment by atom0s** [comment]
Currently, this is not possible. I probably do not have any plans to add this to this version of Steamless either. Perhaps in a future version though.

**Comment by oureveryday** [comment]
https://github.com/oureveryday/Steamless_CLI 
Here is my modded CLI version

**Comment by atom0s** [comment]
Steamless v3.1.0.0 is now released which includes a new command-line tool. Info on the available arguments/options can be found in the release notes here:
https://github.com/atom0s/Steamless/releases/tag/v3.1.0.0

**Comment by Kiefy** [comment]
Thank You!
