### ISSUE TITLE
Steamless can't unpack the executable of the Code 7 game

### ISSUE THREAD

**Issue by jkinnunen** [atom0s/Steamless#18]
Steamless can't unpack the executable of the Code 7 game, not even with the experimental features enabled. Can something be done about this? It would be great to be able to play this game without Steam.
[Here](https://github.com/atom0s/Steamless/files/3091085/Code7.zip) is the executable if you want to take a look at it.

**Comment by atom0s** [comment]
This game is not packed. And does not include Steamstub.
