### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by mirh** [atom0s/Steamless#2]
http://stackoverflow.com/questions/17335712/why-cant-windows-7-load-the-assembly-presentationframework-aero2
http://stackoverflow.com/questions/33378790/presentationframework-aero-aero2-or-aerolite

On other news.. Should I expect this to be the right repo then?

**Comment by atom0s** [comment]
> On other news.. Should I expect this to be the right repo then?

As I stated on the official forums where I release info about this project, yes. This is the repo for Steamless v3 from this point forward.

**Comment by atom0s** [comment]
v3.0.0.2 is now released which should resolve this issue.

**Comment by mirh** [comment]
> As I stated on the official forums where I release info about this project, yes. 

It wouldn't hurt to know where official forums are in the first place ( ͡° ͜ʖ ͡°)

**Comment by atom0s** [comment]
It is right on the main screen of Steamless when you start it.

http://i.imgur.com/9u5YEmX.png

**Comment by mirh** [comment]
Cool, sorry. 
Besides, I'm not really sure why you are complaining about lack of population on gitlab, when you have been missing for 10 months there

**Comment by atom0s** [comment]
I am just going to lock this as you seem to want to be cocky about this.
