### ISSUE TITLE
Cant unpack Tomb Raider Legend

### ISSUE THREAD

**Issue by sergey3695** [atom0s/Steamless#22]
https://store.steampowered.com/app/7000/

[trl_.zip](https://github.com/atom0s/Steamless/files/3330190/trl_.zip)

**Comment by hgdagon** [comment]
Tomb Raider: Legend is DRM-Free on Steam. There's nothing to unpack.

**Comment by atom0s** [comment]
> Tomb Raider: Legend is DRM-Free on Steam. There's nothing to unpack.

The version linked above is protected with SteamStub. 


This version appears to be pretty old, potentially a very early 2.x version or even 1.x. The header is basic xor encrypted like other versions, but there is no signature check. Afterward; the basic setup calls look to be normal but the OEP is just directly invoked from the stub. This is not typical for any of the stub versions I have seen before.

Unpacking this file looks straight forward to do manually by taking the OEP and just replacing it in the header then removing the .bind section. (I didn't dig into the file much; but doesn't look like the text section has any protection/modification either.)

This version seems to be very light-weight/straight-forward to just try and prevent people from just directly sharing the game and not really anything else.

**Comment by atom0s** [comment]
This variant is now supported and has been named 'v1.0 (x86)' as it looks to be like an early edition of SteamStub before any of the other supported variants that I have made plugins for.
