### ISSUE TITLE
Can't unpack Evolve Stage 2 (Legacy)

### ISSUE THREAD

**Issue by phasze** [atom0s/Steamless#23]
https://store.steampowered.com/app/273350/Evolve_Stage_2/

I've uploaded the .exe here since it is greater than 10MB which is github's limit.

https://mega.nz/#!C09kzKiL!VL0Opbh5v63X8wk3rGV1fC2-FVm-Z-jMD1-iMutRuA0

![image](https://user-images.githubusercontent.com/2495331/62902437-d57d3f80-bd1c-11e9-86d8-30105d6d498a.png)

**Comment by atom0s** [comment]
This game is not packed/protected by the SteamStub system.

**Comment by phasze** [comment]
Dang I feared that would be the case, well thanks for checking for me.
