### ISSUE TITLE
Leave one .exe extension in the file name after unpacking.

### ISSUE THREAD

**Issue by oldman777** [atom0s/Steamless#24]
The .exe extension is hidden in Windows, and this is what creates confusion for many people.
As a result, the extension .exe remains twice, after renaming - "EXAMPLE.exe.exe".
Now "EXAMPLE.exe" after unpacking "EXAMPLE.exe.unpacked.exe".
Is it possible to change the file name after unpacking to "EXAMPLE.unpacked.exe"?
This would prevent a bunch of questions about renaming.

**Comment by OdinVex** [comment]
I'd rather keep the renaming. It prevents one from accidentally overwriting your original executable.

**Comment by oldman777** [comment]
> I'd rather keep the renaming. It prevents one from accidentally overwriting your original executable.

Accidentally overwriting "EXAMPLE.exe" by "EXAMPLE.unpacked.exe"?

**Comment by atom0s** [comment]
I haven't had/gotten 'a bunch of questions' about renaming overall. Very rarely actually. Most people that have an interest in using Steamless are generally those that have some sort of interest in reverse engineering or modding. In that sense, most are aware of how to enable visible file extensions on Windows.

Personally, I don't see this is an issue or something I'd be interested in changing.
