### ISSUE TITLE
SizeOfImage is incorrectly calculated

### ISSUE THREAD

**Issue by OdinVex** [atom0s/Steamless#27]
Some PE32s feature Sections out of order. A loop in RebuildSections adding together VirtualAddress and VirtualSize aligned to SectionAlignment (according to PE32 Specification) should be used to determine the 'biggest that will be mapped' into memory and accurately, the SizeOfImage.

**Comment by atom0s** [comment]
This is already a planned addition/fix; related to this issue as well: https://github.com/atom0s/Steamless/issues/17

**Comment by OdinVex** [comment]
Yeah I fixed the calculations on my fork but I didn't think you'd agree with the way I did it. Also added the optional CRC options (but not pushed to my branch yet).

**Comment by atom0s** [comment]
This is fixed in latest source/repo now. Will be in the next release.
