### ISSUE TITLE
Unable to unpack Endless Legend and Endless Space

### ISSUE THREAD

**Issue by alexpersico-1988** [atom0s/Steamless#28]
Hi, I don't find any option useful to unpack both games. It doesn't detect any valid variant so I tried all individually but nothing happens. Only a message **[Steamless] Failed to unpack file**.

Thanks

**Comment by OdinVex** [comment]
Are you talking about Endless Space with Steam appId 208140? If so...it shouldn't work. Because it isn't packed to begin with...

Recommend closing issue.

**Comment by alexpersico-1988** [comment]
Yes, appid 208140. Ok. Thanks.
