### ISSUE TITLE
Black ops 3 not unpacking

### ISSUE THREAD

**Issue by superretro2018** [atom0s/Steamless#29]
I’ve tried unpacking black ops 3 but it says unpacking failed the game is using steams drm could this game be made to be unpacked?

**Comment by OdinVex** [comment]
SteamDRM is not the only DRM that software can use. Softwares these days (especially on Steam) tend to use multiple DRMs. I'd wager BO3 probably uses another DRM on top of things. You should verify that SteamDRM is the only DRM BO3 is using.

**Comment by superretro2018** [comment]
I checked it uses only steam drm no other launcher is used or drm I assume

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OdinVex** [comment]
What did you "check" to determine this?

**Comment by atom0s** [comment]
I would need the exe to determine if there is an issue or if the game is even packed with SteamStub. If you can upload just the exe(s) the game has somewhere that would be great.

**Comment by superretro2018** [comment]
For sure I can email them to you what’s your email?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atom0s** [comment]
You can link to it here or send me a private message on my personal site: atom0s.com

**Comment by superretro2018** [comment]
https://drive.google.com/drive/u/0/folders/1UyuGyAgs6wRFQjZR0QFLwfTTW2vQxb6Y

**Comment by atom0s** [comment]
This game is not packed with SteamStub.
