### ISSUE TITLE
Steamless.NET mysteriously fails on SteamStub Variant #2 when input path has no slash

### ISSUE THREAD

**Issue by SamB** [atom0s/Steamless#3]
It goes something like this:

```
C:\Program Files (x86)\Steam\SteamApps\common\Skyrim>C:\Users\Sam\Source\Repos\S
teamless.NET\Steamless.NET\bin\x86\Debug\Steamless.NET.exe TESV_unpack.exe
==================================================================

>> Steamless.NET v1.0.0.3

(c) 2015 atom0s [atom0s@live.com]
For more info, visit http://atom0s.com/
Special thanks to Cyanic for his research/help.
==================================================================

[!] Info: Found the following unpackers (internal):
[!]  >> Unpacker: SteamStub Variant #1 - by: atom0s (thanks to Cyanic)
[!]  >> Unpacker: SteamStub Variant #2 - by: atom0s (thanks to Cyanic)
[!]  >> Unpacker: SteamStub Variant #3 - by: atom0s (thanks to Cyanic)

[!] Info: File is packed with SteamStub Variant #2!
[!] Info: Unpacker Stage #1
[!] Info: Unpacker Stage #2
[!] Info: Unpacker Stage #3
[!] Error: Failed to read/dump SteamDRMP.dll from file.

[!] Error: Failed to process file.

Press any key to exit...
```

(Incidentally, dropping the severity text from the output would have some unfortunate effects on copy/pasted output, in addition to the potential problems for color-blind people.)

Anyway, it turns out that this code is responsible:

```cs
                // Obtain the path of the current file..
                var basePath = Path.GetDirectoryName(this.File.FilePath);
                if (string.IsNullOrEmpty(basePath))
                    return false;
```

It turns out that [`Path.GetDirectoryName`](https://msdn.microsoft.com/en-US/library/system.io.path.getdirectoryname.aspx) legitimately returns empty strings for relative paths that do not contain any directory separators, and [`Path.Combine`](https://msdn.microsoft.com/en-us/library/system.io.path.combine.aspx) handles these appropriately.  So failing on the empty string here is counter-productive.  (Also, it's not terribly likely that we'll see a null here: that can probably only happen with *very* unlucky root directories on OSes like BSD where it's possible to open directories as files and read bytes out of them.)

**Comment by atom0s** [comment]
It looks like you are using an old version of Steamless. The newest version is 2.0. Please update and see if the problem still persists.
