### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by ghost** [atom0s/Steamless#4]
I don't know at all how to use this tool, and I'm sure many people have the same issue.
There's only:

> **Compiling Steamless**
> 
> Steamless is coded using Visual Studio 2015 (Update 3) at this time.
> To compile, you should only need to load the sln file and compile as-is.
> 
> No changes should be needed to the solution or source.

**Comment by atom0s** [comment]
If you can't figure out how to compile the source code, then it is probably best you just use the precompiled releases. Anyway this is not a bug, so closing this.

**Comment by ghost** [comment]
@atom0s Sorry, I missed precompiled releases completely - they didn't exist before the tool was moved to Github as far as I know.

**Comment by atom0s** [comment]
> @atom0s Sorry, I missed precompiled releases completely - they didn't exist before the tool was moved to Github as far as I know.

No worries, they don't make it that easy to spot sadly. Github could use a little bit of a cleanup to their site UI. Releases get missed pretty often on a lot of projects.
