### ISSUE TITLE
Unable to unpack Back4Blood

### ISSUE THREAD

**Issue by ghost** [atom0s/Steamless#42]
Nothing special in the log, it just fails after "Exampl plugin was asked[...]"

**Comment by atom0s** [comment]
Be sure to extract everything into a folder, don't run Steamless directly from the zip otherwise the plugins will not load.

**Comment by ghost** [comment]
> don't run Steamless directly from the zip

I can assure you I'm not a moron and used Steamless before multiple times.
I've tested on another game and it works just fine. B4B binary is 400MB, btw, might be what makes Steamless spasm and die

**Comment by atom0s** [comment]
Feel free to upload the exe somewhere and I can take a look.

**Comment by OdinVex** [comment]
I sometimes encountered @DigikaZ's situation over a year ago when I was modifying Steamless to clean up the stub and add some custom behavior.
@DigikaZ You may need to download Steamless src and debug backwards on your own. I found a few lines that made some assumptions and would silently cascade fail out and make things look as if nothing was happening or running. *Edit* By the way, at 400MB, seems like either a lot of padding or Denuvo/DRM.
