### ISSUE TITLE
Wargroove unpacked witth success, impossible to launch

### ISSUE THREAD

**Issue by shenron** [atom0s/Steamless#47]
Hello,

When I try launch wargroove I have this error:

![image](https://user-images.githubusercontent.com/907354/107130696-7a57e900-68d0-11eb-9266-8d1885688f73.png)

Someone has an idea?

Thank you :)

**Comment by atom0s** [comment]
Steamless does not entirely remove the requirement to run games through Steam. As the error says, it detected it was not launched via Steam. Either the game has it's own means of checking or it is using steam_api.dll to ensure it's running via Steam. Run the game as it should be via Steam. (Rename the original exe and replace it with the unpacked one and run normally via Steam.)

This project is not for piracy. So if the goal is to run a game you don't own without Steam, then this is not the place for help with that.

**Comment by tcastelly** [comment]
Thank you for your answer.

I bought the game twice (Switch / PC), my idea was to launch it without steam on Gnu Linux (just with Wine).
