### ISSUE TITLE
Run Steamless over command line

### ISSUE THREAD

**Issue by javster101** [atom0s/Steamless#48]
I would like to include Steamless in a mod manager to automatically run it when setting up a game.
Is there some sort of command line interface for Steamless?

**Comment by atom0s** [comment]
> I would like to include Steamless in a mod manager to automatically run it when setting up a game.

Steamless is not aimed to be bundled with other projects. Please instead direct people to this repo/downloads page if there is a need for it in your project.

> Is there some sort of command line interface for Steamless?

No. The current version has no command-line features for unpacking.
