### ISSUE TITLE
Unable to unpack BlazBlue Calamity Trigger

### ISSUE THREAD

**Issue by ii3eas7** [atom0s/Steamless#49]
EXE cannot be unpacked using Steamless v3.0.0.11.  Using experimental features will "successfully" unpack the exe, but if you use this unpacked exe to play the game will crash.  Is it possible this is related to SteamStub 2.0?

[BBCT.zip](https://github.com/atom0s/Steamless/files/6146805/BBCT.zip)

**Comment by DarkFrost89** [comment]
Posibbly BlazBlue Calamity Trigger is have custom secure code
You Need to Looking This
https://gamecopyworld.com/games/pc_blazblue_calamity_trigger.shtml#Blazblue:%20Calamity%20Trigger%20[MULTI8]%20No-DVD/Fixed%20Image
Protection is Custom Code (Settec Alpha ROM + Themida)

**Comment by atom0s** [comment]
> Protection is Custom Code (Settec Alpha ROM + Themida)

This file is not packed/protected with Settec Alpha ROM or Themida. 

> Using experimental features will "successfully" unpack the exe, but if you use this unpacked exe to play the game will crash.

Do you get any specific error? The resulting file while using the experimental features option looks fine at first glance.  The game appears to create an 'assert.txt' error log while it runs, also if you can post that here that'll help see what may be failing.

**Comment by ii3eas7** [comment]
Here's [assert.txt](https://github.com/atom0s/Steamless/files/6550098/assert.txt), but it doesn't appear to contain much.  Unfortunately I don't get any errors, it just crashes when I press enter/start on the main menu.

**Comment by atom0s** [comment]
Late reply, but that assert log shows the game is attempting to load meaning its beyond a crash that would probably involve Steamless. In some cases the game may require/expect the exe to be named something specifically, something common with engines like Unreal. If the original exe had a weird name like `Something-Win32-Shipping.exe` then be sure to rename the unpacked file to the original name and place it where the original was. (Be sure to backup the original exe as well first.)

**Comment by atom0s** [comment]
Closing this as the error given does not look to be due to Steamless.
