### ISSUE TITLE
"To the Moon"

### ISSUE THREAD

**Issue by ghost** [atom0s/Steamless#5]
http://store.steampowered.com/app/206440/

Unpacking "works" and there are no errors, when attempting to launch the game from new executable:

![2017-01-25 16_19_30-to the moon](https://cloud.githubusercontent.com/assets/14923168/22293959/30e71470-e31a-11e6-8aca-e4b3690a4ded.png)

[Protectionid ](http://pid.gamecopyworld.com/) still detects Steam.
The original .exe: https://dropfile.to/udKhqYM

**Comment by atom0s** [comment]
Steamless does its job properly and removes SteamStub. If the game further requires Steam, then you will need to figure out what it requires and move that layer yourself. Steamless will not 100% remove Steam on all games that use things like the SteamAPI or other checks. Steamless will only remove the packer DRM portion of the protections. 

From what I see with this exe, it does not use SteamAPI so it is using some other method of determining if Steam is running. The one main thing I would look into, is the game loads a module based on an environment variable.


    GetPrivateProfileStringA("Game", "Library", Default, &ReturnedString, 0x200u, &FileName);
    GetPrivateProfileStringA("Game", "Title", "Untitled", &WindowName, 0x200u, &FileName);
    GetPrivateProfileStringA("Game", "Scripts", Default, &v36, 0x200u, &FileName);

Later on it attempts to load what was passed to Library:


    v23 = LoadLibraryA(&ReturnedString);
    v24 = v23;
    hLibModule = v23;
    if ( !v23 )
    {
    v25 = GetLastError();
    v73 = v25;
    if ( v25 == 126 )
    {
      v25 = -2147287038;
      v73 = -2147287038;
    }
    Arguments = &ReturnedString;
    FormatMessageA(0x3000u, 0, v25, 0x400u, &Buffer, 0x400u, &Arguments);
    MessageBoxA(v16, &Buffer, &WindowName, 0x10u);
    goto LABEL_35;
    }

So be sure you are launching the game in a way these are being populated and correct. (You may need to make your own batch file to launch the game after its unpacked.)
