### ISSUE TITLE
Problem Unpack Steam Stub 3.1 (X86) & 3.0 (X64)

### ISSUE THREAD

**Issue by DarkFrost89** [atom0s/Steamless#50]
Hi atom0s ı have issue unpack Steam Stub 3.1 (X86) & 3.0 (X64) game carmageddon max damage and metal gear solid ground zeroes,
if ı unpack the files (Note:I Use Steamless 3.0.0.11), files are unpacked but not work with game can you fix this problem please
ı upload orginal and stubbed files this link 
carmageddon max damage Steam Stub 3.1 (X86)
https://www.filecad.com/aloX/CGMD.7z
gear solid ground zeroes 3.0 (X64)
https://www.filecad.com/aloZ/MGS.7z

**Comment by ghost** [comment]
Do those even use steam stub? Even if they do, are you sure they don't use another form of DRM? Like the usual steam_api.dll or some other?

**Comment by atom0s** [comment]
Both of these games use SteamStub but also use the SteamWorks API layer (steam_api.dll / steam_api64.dll) meaning you will still need to ensure that Steam is running properly for the games to launch. For that, you can generally rename the original exe to a different name and rename the unpacked exe to the original game exe name and put it where the original was. 

This project does not remove, emulate or assist with removing the SteamWorks API layer. 
Outside of that, the files unpack fine.
