### ISSUE TITLE
I cannot unpack Dragon Ball FighterZ.exe

### ISSUE THREAD

**Issue by cherishyourlife** [atom0s/Steamless#53]
Hey,

I tried  unpack Dragon Ball FighterZ with steamless but it didnt work for me.

https://store.steampowered.com/app/678950/

[DBFighterZ.zip](https://github.com/atom0s/Steamless/files/6874662/DBFighterZ.zip)

Thank you!

**Comment by atom0s** [comment]
This file is not protected/packed with SteamStub.
