### ISSUE TITLE
Unable to unpack Dead or Alive Xtreme Venus Vacation

### ISSUE THREAD

**Issue by Mrblubb** [atom0s/Steamless#54]
DOAX_VV.exe cannot be unpacked using Steamless v3.0.0.11 with or without experimental features. Shows error "Failed to unpack the file."
![Screenshot (12)](https://user-images.githubusercontent.com/88938655/129450924-86722099-6e91-4c6e-b0bc-8cdc6d01d434.png)

**Comment by atom0s** [comment]
I would need a copy of the exe to take a look as to why it fails.

**Comment by Mrblubb** [comment]
Sure, Here it is https://we.tl/t-xt05dvxKuw

**Comment by atom0s** [comment]
Neither of these files are packed with SteamStub.
