### ISSUE TITLE
Failing to unpack on newer windows versions?

### ISSUE THREAD

**Issue by DemigodKushal** [atom0s/Steamless#55]
I’ve tried unpacking three games. Stride, HL-2 and Titan souls. Failed all three times. Last time (In may) I tried unpacking Stride, it worked flawlessly. The only thing that has changed since is my windows version. Please look into it. Amazing tool btw.

**Comment by atom0s** [comment]
You need to post the exe's somewhere otherwise nothing I can do.

**Comment by DemigodKushal** [comment]
`aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xb285eDJXWGVCM0VkS3NyNVV0aDYzTlRRLWp4NjQ5Nlcvdmlldz91c3A9c2hhcmluZw==`

Encoded in base 64 to avoid Github terming stuff. this is stride.

**Comment by atom0s** [comment]
> `aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xb285eDJXWGVCM0VkS3NyNVV0aDYzTlRRLWp4NjQ5Nlcvdmlldz91c3A9c2hhcmluZw==`
> 
> Encoded in base 64 to avoid Github terming stuff. this is stride.

This file is not packed with SteamStub.

**Comment by DemigodKushal** [comment]
`https://www70.zippyshare.com/v/F84XNFKU/file.html`

try this. I'm pretty sure Stride had steam drm but whatever.


Edit: figured out what was happening. Sorry for any inconveniences. This comment may be ignored.

**Comment by atom0s** [comment]
> `https://www70.zippyshare.com/v/F84XNFKU/file.html`
> 
> try this. I'm pretty sure Stride had steam drm but whatever.
> 
> Edit: figured out what was happening. Sorry for any inconveniences. This comment may be ignored.

This file is also not packed with SteamStub.
