### ISSUE TITLE
Unable to unpack Songs Of Wuxia

### ISSUE THREAD

**Issue by oureveryday** [atom0s/Steamless#56]
[Songs_Of_WuXia.zip](https://github.com/atom0s/Steamless/files/7068280/Songs_Of_WuXia.zip)
I am sure it's SteamStub but it not works......

**Comment by atom0s** [comment]
This file has a block of memory that matches a pattern that is not part of the header being scanned. Until I have time to fix it, here's the file unpacked.

[Songs_Of_WuXia.exe.unpacked.exe.zip](https://github.com/atom0s/Steamless/files/7072152/Songs_Of_WuXia.exe.unpacked.exe.zip)

**Comment by atom0s** [comment]
This is now fixed in latest source in the repo, will be in the next release soon.
