### ISSUE TITLE
I can't unpack The Sinking City (the current Steam version)

### ISSUE THREAD

**Issue by ancient-animal** [atom0s/Steamless#58]
It's 406 MB.

It's the largest EXE file I've ever seen.

I tried unpacking it with version 3.0.0.11 and version 3.0.0.12 of Steamless.

I gave permission to atom0s to access it here (the invitation to the repository must be accepted):
https://github.com/ancient-animal/a-file-for-assistance/releases

**Comment by atom0s** [comment]
This file is not packed with SteamStub.

**Comment by ancient-animal** [comment]
I did not know that. Other people on the Steam forum haven't mentioned that. 

I'm sorry for bothering you.

**Comment by atom0s** [comment]
> I'm sorry for bothering you.

Not a bother. :) _Sorry for the late reply._
