### ISSUE TITLE
Failed to unpack every exe file，but it used to work fine.

### ISSUE THREAD

**Issue by 670233975** [atom0s/Steamless#59]
[ExamplePlugin] ExamplePlugin was asked to check if it can process a file!
[Steamless] Failed to unpack file.

It happens one every game. This is strange. I'm pretty sure some of the exe files could be unpack successfully before.Maybe it's a problem with my system？I can't think of any settings I've changed.This happened when I was using v3.0.0.12, I switched to v3.0.0.11 and it also failed to unpack.

**Comment by atom0s** [comment]
You need to extract all the files included with Steamless' release package. Otherwise, it will not fully work properly. 
Do not run it from the zip file itself.

**Comment by 670233975** [comment]
I compared the files in the folder with the files in the zip,they are the same.So the problem looks like it's caused by missing files?I turned off the firewall, but it still failed to unpack.

**Comment by iCrazeiOS** [comment]
Just tried using Steamless for the first time - have the same issue. Same error message with every game.

**Comment by atom0s** [comment]
If there are specific exe's not working then you need to upload them somewhere and link to them here. I can't fix issues without seeing what the actual problem(s) are. Just telling me `it doesn't work` is not helpful at all.

**Comment by atom0s** [comment]
> Just tested 6 games, and only 1 properly worked (GTA 3). Here's the other games I tried (not working): https://filebin.net/ya509kqx6mpm4mhn

```
adventure-capitalist.exe -- Not packed with SteamStub.
Among_Us.exe             -- Not packed with SteamStub.
left4dead2.exe           -- Not packed with SteamStub.
Rust.exe                 -- Not packed with SteamStub.
Terraria.exe             -- Not packed with SteamStub.
```
