### ISSUE TITLE
Failed to unpack SteamStub 2.0

### ISSUE THREAD

**Issue by DarkerSquirrel** [atom0s/Steamless#6]
[RBDXSteam_zip.zip](https://github.com/atom0s/Steamless/files/1458031/RBDXSteam_zip.zip)

**Comment by atom0s** [comment]
This file is not packed with SteamStub.

**Comment by atom0s** [comment]
(Sorry for the spam, if you got emailed, I read the wrong tab and responded to the wrong issue.)

Looking into this to see what the issue may be.

**Comment by atom0s** [comment]
This issue is now fixed with commit 18d34ede4d375f7f4cde37e084cde6761bae7c71

Added new release with this built in.
https://github.com/atom0s/Steamless/releases

**Comment by DarkerSquirrel** [comment]
Thanks v much for your effort , At0m0s.

Dont worry about the spam , I am flooded anyway :-D
