### ISSUE TITLE
Fails with Medal of Honor 2010

### ISSUE THREAD

**Issue by chestfindman** [atom0s/Steamless#61]
I'm probably missing something or doing something wrong, maybe it's something on my end.
Link to executable -> [moh.exe](https://pixeldrain.com/u/wgvebv71)
(Let me know if you need another file host, or anything else I can provide)

File SHA1: e5148aace260399914c4572d9f4f3c697e6ba7df (as verified by [SteamDB](https://steamdb.info/depot/47791/?show_hashes), just in case)

Note that the game is also protected by SecuROM, this might be what's interfering?
I've already activated my key for it, the game runs as intended through Steam, gives the classic SteamStub error when launched otherwise.

Apologies, I'm not very proficient at this. This is all I got from Steamless [capture](https://i.ibb.co/cCVPGqW/image.png)

**Comment by atom0s** [comment]
The file is indeed protected with SecuROM as well. The issue is that they used SecuROM after using Steam's DRM so you must remove SecuROM first before SteamStub can be removed. 

Doing this is outside of the scope of this project.

**Comment by chestfindman** [comment]
Understood, that is what I was worried about too, the SecuROM activation window pops-up before anything else, and SteamStub comes into play after it's dealt with.

Thank you for taking a look anyway.
