### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by LookslikeLenni** [atom0s/Steamless#66]
Ok I read the Readme 10 times and the Issues, if someone had the same problem, and downloaded it and opend it and tryed to run it, but I have NO clue of what im doing. Is there some tutorial I missed or how do I use it? (I want to Steamlessify AC7 for the Ultrawide mod).

**Comment by atom0s** [comment]
The UI is as basic as it gets... Either drag and drop the file into the path area of the window or manually select it with the button and click 'Unpack File'.

**Comment by father6800-pixel** [comment]
where is the sln file
