### ISSUE TITLE
Atelier Rorona and Totori not unpacking, Atelier Meruru is

### ISSUE THREAD

**Issue by BeauTaapken** [atom0s/Steamless#67]
Hi, when trying to unpack the Atelier Rorona english exe or Atelier Totori english exe it gives me the following error no matter the options or plugin I select: [Steamless] Failed to unpack file. I attached both exe's in zip files
[A11R_x64_Release_en.zip](https://github.com/atom0s/Steamless/files/7963907/A11R_x64_Release_en.zip)
[A12V_x64_Release_en.zip](https://github.com/atom0s/Steamless/files/7963908/A12V_x64_Release_en.zip)
.

**Comment by atom0s** [comment]
These files are not packed with SteamStub.
