### ISSUE TITLE
Unable to unpack Atelier Sophie 2

### ISSUE THREAD

**Issue by makc-ar** [atom0s/Steamless#68]
Example .exe https://dropmefiles.com/pU3AM

**Comment by atom0s** [comment]
This file appears like it is already cracked/bypassed. The `.bind` section does exist but it isn't be used at all. The entry point is in the normal `.text` section and the `.text` section is also not encrypted at all.

The present TLS callbacks are all within the normal binary space too. 

Just delete the `.bind` section with another PE editor like CFF Explorer and it should run fine as is.
