### ISSUE TITLE
Thanks to the author for the contribution, it was very helpful for me. But there is a problem when i remove the drm from final fantasy 13

### ISSUE THREAD

**Issue by violetteflutter** [atom0s/Steamless#69]
![新建位图图像](https://user-images.githubusercontent.com/79825377/158050338-61834d85-8aaf-4608-ad32-9115be8f271b.png)
Here is the exe file.
[ffxiiiimg.zip](https://github.com/atom0s/Steamless/files/8239143/ffxiiiimg.zip)
Thanks again

**Comment by atom0s** [comment]
Use the option `Use Experimental Features` and it should work for this file.
