### ISSUE TITLE
Bad Unpacking

### ISSUE THREAD

**Issue by marcussacana** [atom0s/Steamless#7]
I'm trying mod a game egine allowing I translate it, to this i need remove the steam stub, but using the steamless the game don't start, I tried force the game run using the debugger but no lucky
Game: http://store.steampowered.com/app/745960/A_Sky_Full_of_Stars/

You need the unpack/packed executable?

**Comment by atom0s** [comment]
I would need the packed exe to take a look.

**Comment by marcussacana** [comment]
Here, included some dlls required to start
[Base Engine.rar](https://github.com/atom0s/Steamless/files/1588432/Base.Engine.zip)

**Comment by atom0s** [comment]
Something to try:

  * Unpack the file.
  * Rename the original game file to AdvHD.exe.bak
  * Rename unpacked file to AdvHD.exe

Try to stat the game then. If still nothing, add a file in the games folder (where the exe is) named steam_appid.txt and put the following in the file, nothing else: 
745960

**Comment by marcussacana** [comment]
Okay, thx, Creating the steam_appid.txt he launch, but how the process continue closes when debugging i can supose the executable contains more one protection?

**Comment by marcussacana** [comment]
Srry for disturb, I can debug if I attach the debugger after the game launch....
