### ISSUE TITLE
Steamless.API.dll is still required to be in the same folder as the CLI executable after c2719b776d77ed2855443067d9c1c127a4fdc935

### ISSUE THREAD

**Issue by layercak3** [atom0s/Steamless#75]
`CLI: Fix issues where Steamless.API.dll was required to be in the same folder as the CLI executable.` in c2719b776d77ed2855443067d9c1c127a4fdc935 doesn't appear to work (Steamless.CLI.exe crashes on launch if it's not in the  same folder because of [CLI: Fix Steamless.API.dll reference being copied to main output folder.](https://github.com/atom0s/Steamless/commit/c2719b776d77ed2855443067d9c1c127a4fdc935#diff-b66edfaa8d3321a09881f2d18e8fee1502c56012cdc6753fdc507e0eabcf72e3R59)). Steamless.API.dll is still required to be in the same folder as the CLI executable.

Reversing https://github.com/atom0s/Steamless/commit/c2719b776d77ed2855443067d9c1c127a4fdc935#diff-b66edfaa8d3321a09881f2d18e8fee1502c56012cdc6753fdc507e0eabcf72e3R59 or manually copying the API dll from `Plugins` to the main output folder allows the program to launch again.

**Comment by atom0s** [comment]
If you're compiling from source yourself and running within a debugger, be sure that you have set the proper working path for your environment. The current release (3.1.0.0) is working fine with the API files and plugins within the `Plugins` folder as expected. 

I am not able to reproduce any issues/errors on multiple test machines either with the latest release package, and with the direct source with a proper environment setup.

**Comment by layercak3** [comment]
Ok, I'm building the source (latest commit in master) using mono msbuild for Linux (patches irrelevant to the issue were needed to get it to build) in a clean environment (so not caused by cache etc.). Could be an issue with mono/msbuild then.

**Comment by Tuupertunut** [comment]
My workaround for this issue on Linux is to set `MONO_PATH=Plugins` before running the program.

**Comment by Arcitec** [comment]
@Tuupertunut The fault is with Steamless. By default, the .NET runtime looks for libraries in the application's current folder or the Global Assembly Cache (GAC). I'll submit a pull request with the code fix for Steamless. It's super tiny.
