### ISSUE TITLE
Xenus 2 crashes after unpack

### ISSUE THREAD

**Issue by daci12345** [atom0s/Steamless#77]
The exe: https://gofile.io/d/fBl8ry
It only unpacks after enabling the experimental settings, i tried with and without keeping the bind section, the game crashes with both of the exes.

**Comment by atom0s** [comment]
I don't own this game so I cannot do any extended testing. However, Steamless appears to process the file fine, and the resulting output looks like it should work fine. 

Any additional crashing may happen due to extra protections that the game may be using.
