### ISSUE TITLE
Basic usage guide well hidden or missing

### ISSUE THREAD

**Issue by theCrius** [atom0s/Steamless#78]
Releases are well visible (right side of the main page of the repo) but still, after downloading the latest release I could only guess that I needed to open the `Steamless.exe` and then load up the exe I wanted this application to work on.

After a nice "success" message, clicking the unpacked version simply tells me that there should be an "unpacked" directory which is not there.

A simple guide on what the user should do and what should happens would help using this tool. At least would point people in the right direction if something is actually not going in the right direction with the process.

Nothing fancy is required, even a simple readme like in the Goldberg's project would suffice compared to nothing.

**Comment by theCrius** [comment]
This is after searching inside a known forum that however won't appear in google results if you search for `steamless`.

> Q(C04): The game doesn't start, it just opens Steam or shows an "Application load error 3:0000065432"-message, what should I do?
>A: This message indicates that the game's .exe is protected by SteamStubDRM.
> One way to remove it is by using Steamless:

> 
> 1. Start Steamless and select the game's .exe.
> 2. Make sure the plugin is set to "Automatic" and "Keep Bind Section" is checked.
> 3. Click the "Unpack File"-button.
> 4. In the game folder, rename or move the original .exe, then rename the newly unpacked one. Example: "game.exe.unpacked.exe" to "game.exe". Make sure you let Windows display file extensions to do this properly.

Something basic as this is more than enough but should be inside this repo readme.md or something like that.

**Comment by atom0s** [comment]
Steamless is not for piracy or cracking games. I opt to leave out basic / generic instructions because this is not a tool intended for non-developers that just want to crack games or remove parts of Steam to try to bypass paying for things. I have no plans to add any kind of docs like this because of this.

**Comment by theCrius** [comment]
I never implied that it was for that purpose but that's the only instructions found anywhere.

I wonder what is the scope of the project as the only "will do" section of the readme is "remove steamSTUB" which is a DRM.
https://www.gog.com/forum/general/what_is_steamstub_drm
