### ISSUE TITLE
Failed to Unpack File

### ISSUE THREAD

**Issue by Marold57** [atom0s/Steamless#79]
Hello.

I got "[Steamless] Failed to unpack File" when i try to unpack the two exe Files.  The First is in the Zip and the other is in the Link here: https://files.fm/f/ye4b33tfn
Both Files a from the same Game from Steam.
Thanks and have a nice day !

[SpaceHulkDeathwing.zip](https://github.com/atom0s/Steamless/files/9269172/SpaceHulkDeathwing.zip)

**Comment by atom0s** [comment]
This file is not packed with SteamStub.
