### ISSUE TITLE
All the unpacking works but then it fails when it tries to save, what should I do

### ISSUE THREAD

**Issue by amperk1** [atom0s/Steamless#82]

**Comment by atom0s** [comment]
You are most likely trying to unpack a file that is in a secured folder of sorts. Generally, this means that Steamless is being ran as a non-Administrative user and you are trying to unpack a file that is within a system folder. (ie. `C:\Program Files\...`) Either run Steamless as administrator `(Right-click > Run as Adminstrator)` or copy the file you are trying to unpack somewhere else that you have access to.
