### ISSUE TITLE
Problem applying Steamless to F.E.A.R.

### ISSUE THREAD

**Issue by TiredEyesThomas** [atom0s/Steamless#83]
I am using Creative Alchemy as recommended on the PCGamingWiki to restore EAX audio effects. 
Using Steamless however lead to the game giving me an error and no sound.
"Failed to initialize SndDrv.dll"

(The reason I want to apply Steamless is because another fix on the wiki recommends using a patch to modify the exe in order to grant the game 4 instead of 2 gb of memory. The wiki says one should use steamless and the game indeed does not open and displays a steam error.)
(Also: my setup is Windows 7)
(Also starting the exe in admin and xp compatibility mode as EAX wont get unlocked otherwise.)

**Comment by atom0s** [comment]
Steamless' goal is to simply unpack the file. Any issues that happen with the file after the fact are not within the scope of this project. You would need to figure out and fix any issues with the game running unpacked yourself, sorry.
