### ISSUE TITLE
Machinarium

### ISSUE THREAD

**Issue by proxpro200** [atom0s/Steamless#84]
Machinarium unpack error

I think SteamLess needs an update

**Comment by atom0s** [comment]
Without a copy of the exe you are trying to unpack, I cannot investigate if this is an actual issue or not.

**Comment by chestfindman** [comment]
The game does not use SteamStub -> [Machinarium.zip](https://github.com/atom0s/Steamless/files/9623176/Machinarium.zip)

**Comment by atom0s** [comment]
Assuming your file is the same as their request, then yes this does not use SteamStub. Will close for now. 
Feel free to attach another file if this game does have a version packed with it that Steamless fails to work on.
