### ISSUE TITLE
Unable to detect if there is any SteamStub in an Exe

### ISSUE THREAD

**Issue by kasha695** [atom0s/Steamless#87]
Thanks for the fix earlier, compiled and works perfectly.

This may not be anything but I've found a set of older exe's that Steamless is unable to find any SteamStub elements.

They may not have any, but when I try to use them i get the error:
`Failed to find Steam.`
And then a web browser opens to the Steam store page.

I've checked all the dll's and other files and I can't seem to find anything being called during the exe initial startup, apart from the mss32.dll file which is Miles audio, after that the error shows.

I'll attach the exe's in case there is some older version in them.
[Exes.tar.gz](https://github.com/atom0s/Steamless/files/9647780/Exes.tar.gz)

Sorry for wasting your time if they don't!

**Comment by atom0s** [comment]
All of these files look to be packed with PECompact. But they are not also packed with SteamStub. They may reference `steamapi.dll` once PECompacts initial unpacking happens at runtime, but that is out of the scope of this project.
