### ISSUE TITLE
Exp feat no works EXEs

### ISSUE THREAD

**Issue by Klemci** [atom0s/Steamless#89]
**Red Johnson's Chronicles - 1+2 - Steam Special Edition**
=
EXEs (x2, 1 by ep.) are BINs files with extension changed, so :  SLess not works, experimental feature enables it unpacking.
EXEs (BINs renamed) **not working afterward, game're not launched.**  (tried all optionsin SLess, and for game : launcher for bin extension (default game's behavior), and exe extension).
[RJChronicl.zip](https://github.com/atom0s/Steamless/files/9761480/RJChronicl.zip)
Found alternative (EXEs work from launcher (need bin extension), and with exe extension independantly too).

**Black Sails - The Ghost Ship**
=
**Same**, but the EXE is an EXE (yep, not a camofled BIN).
[BSail.zip](https://github.com/atom0s/Steamless/files/9761477/BSail.zip)

**Comment by atom0s** [comment]
Hello, these files are all SteamStub v2.1 (x86) which has a known problem with the IAT copying that the protection does.

The IAT is copied into the .bind section and the PE header is updated to point to the copy. This is a known issue that will be worked on later when I have time. Having more samples is a big help though, so thanks for the additional samples. 

For now, as a small work-around, if you unpack these files use the following two options in Steamless:

  - Use experimental features.
  - Keep .bind section after unpacking.

This should keep the files in a state that should still work for now.

**Comment by Klemci** [comment]
ALLRight,

i think i tested this combo of options (quote : tried all options in SLess), all possibilities, just verified right now with this two on te 3 EXEs, nothing, just like if i clicked a fake EXE.

I'll follow future updates, no rush, i found alternative. 

Thanks.

//

Is there a list of v2.1 SteamStub games ?

**Comment by Klemci** [comment]
And too, the RJC "launcher" EXE (no Stub), that uses the two BIN camofled EXEs, it's perhaps helping in researches...

[RJC_BIN-launcher.zip](https://github.com/atom0s/Steamless/files/9762509/RJC_BIN-launcher.zip)

**Comment by gtao725** [comment]
[ffxiiiimg.zip](https://github.com/atom0s/Steamless/files/10096784/ffxiiiimg.zip)
The same thing happens with Final Fantasy XIII. Unpacking only works by using experimental features but the unpacked exe does nothing, game does not launch. I tried Klemci's workaround by renaming the unpacked .exe to .bin and still does not work, regardless of whether I use the launcher or not. Also tried experimental features with keep .bind section and no luck. I hope it gets updated soon. Thank you for this wonderful program though, it works with most other games :)

**Comment by Klemci** [comment]
Prey 2006 EXE : 
[Prey2006_(stub v20).zip](https://github.com/atom0s/Steamless/files/10907599/Prey2006_.stub.v20.zip)

**Comment by atom0s** [comment]
> Prey 2006 EXE : [Prey2006_(stub v20).zip](https://github.com/atom0s/Steamless/files/10907599/Prey2006_.stub.v20.zip)

This issue was already fixed. However, the previous latest release of Steamless wasn't up to date yet. 

This should now be available without having to manually compile using the latest release here:
https://github.com/atom0s/Steamless/releases/latest
