### ISSUE TITLE
Exe fails to unpack SteamStub v3.0

### ISSUE THREAD

**Issue by kasha695** [atom0s/Steamless#91]
Found another game where Steamless detects version 3.0 x86 but fails at Step 1.

Please find attached the exe file

[Exe.tar.gz](https://github.com/atom0s/Steamless/files/9943535/Exe.tar.gz)

**Comment by kasha695** [comment]
And another exe which is very similar, it appears to work but it doesn't work when applied to the game afterwards.

Rename the file to Exe2.7z to extract (avoiding file limit size and dislike of .7z uplaods)
[Exe2.zip](https://github.com/atom0s/Steamless/files/9944005/Exe2.zip)

**Comment by atom0s** [comment]
`trine1_32bit.exe` - Steamless works fine on this file and I see no issue with the resulting binary. If the game has additional safety checks to see if its unpacked or has SteamStub removed, then you would need to fix that yourself separately. 

---

`trine2_32bit.exe` - This file looks to be either already unpacked but with the `.bind` section left in, or it was incorrectly protected. 

Some things to note about this file:

  - The entry point is not changed, it still points to the original within the `.text` section.
  - There are no TLS callbacks that would suggest a different means of calling into the `.bind` section separately.
  - The `.text` section is not encrypted. Meaning SteamStub isn't being used to decrypt it.

This suggests that the file was either already unpacked or not packed correctly in the first place.
