### ISSUE TITLE
Exe fails to unpack SteamStub v3.1

### ISSUE THREAD

**Issue by PaienNate** [atom0s/Steamless#92]
Find a new game named DaveTheDiver will failed to unpack:
Steamless will recognize this but will failed at the step one:
![image](https://user-images.githubusercontent.com/68044286/212531985-597a4b27-96ac-4cce-8e30-c21c298af297.png)

Hope it can become a new useful sample and lot of thanks for your excellent job.
File have been uploaded here:
[DaveTheDiver.zip](https://github.com/atom0s/Steamless/files/10419789/DaveTheDiver.zip)

**Comment by DartPower** [comment]
1. Try to use folder only with EN symbols in name
2. Try to use Automatic unpacker type
3. Try check only these checkboxes: (disable Recalculate checksum)
![image](https://user-images.githubusercontent.com/2005369/212532488-28879c86-e925-4856-aea8-a990eb06ed10.png)

**Comment by PaienNate** [comment]
> 1. Try to use folder only with EN symbols in name
> 2. Try to use Automatic unpacker type
> 3. Try check only these checkboxes: (disable Recalculate checksum)
>    ![image](https://user-images.githubusercontent.com/2005369/212532488-28879c86-e925-4856-aea8-a990eb06ed10.png)

![image](https://user-images.githubusercontent.com/68044286/212532557-77d7ef38-b489-4c2f-8895-01a36d29a01d.png)

Not work too. Actually I have tried lots for choose/not choose these checkboxes, but seems nothing better :(

**Comment by atom0s** [comment]
This file is packed with an additional packer. That would have to be removed first before you can use Steamless on this file.
This is not a bug with Steamless.
