### ISSUE TITLE
No Mans Sky Crashes after Unpacking

### ISSUE THREAD

**Issue by Madeupname722** [atom0s/Steamless#93]
This worked before, they changed something in updates.

Unpack nms.exe
Replace steam_api64.dll with goldberg version.
Start game with unpacked exe.

Game crashes on start every time now.

I did notice that 2 folders are created and deleted inside the games main folder during normal game startup. I don't know if this is new.

FYI I am running the most recent version of the game from Steam, which I own it on,  I just don't want steam running when I play it.

**Comment by atom0s** [comment]
Crashes like this are up to you to figure out and fix.

I do not support piracy or the use of emulation layers such as goldberg.
