### ISSUE TITLE
Call of Duty 4 Modern Warfare

### ISSUE THREAD

**Issue by Hishetora** [atom0s/Steamless#94]
[iw3sp.zip](https://github.com/atom0s/Steamless/files/10915157/iw3sp.zip)
Invalid/unknown variant header size: 884

**Comment by atom0s** [comment]
This issue was already fixed. However, the previous latest release of Steamless wasn't up to date yet. 

This should now be available without having to manually compile using the latest release here:
https://github.com/atom0s/Steamless/releases/latest
