### ISSUE TITLE
REHDHook - please read my comment

### ISSUE THREAD

**Issue by Klemci** [atom0s/Steamless#95]
I commented (it''s the last) but i'm not sure if you look at this RE modding board years later... if ever an update is possible, thanks.

https://residentevilmodding.boards.net/thread/3269/rehdhook-direct3d-hook-plugins-addons?page=8

Sorry to write here about another tool but i couldn't find another way :p

**Comment by atom0s** [comment]
Hello, I don't visit that forum any longer. Sorry to say but I also don't plan to do any more updates to my proxy/mods for those games either. I was gifted the game by someone to do the initial mod/work on it but given how poorly ported and done the game was by CAPCOM, I have no interest in working on it further.

**Comment by Klemci** [comment]
Thanks, no problemo. RE4R looks to have some problems with Ray Tracing !..

Bon week-end.
