### ISSUE TITLE
Game protected with steam VLV stub but steamless fails to unpack

### ISSUE THREAD

**Issue by Aholicknight** [atom0s/Steamless#96]
![die_20230313_WG9Mn8y5kI](https://user-images.githubusercontent.com/7843719/227335631-b7628fb9-e16f-4e74-8b48-6bb21cea34d4.png)

The Counter-Strike 2 beta is protected with a steam stub. When I try to unpack the exe this is what I get when using the latest version:

![dopus_20230313_IDVjbEiLsb](https://user-images.githubusercontent.com/7843719/227335936-9db3ac1c-6096-4a59-b631-f410662ecbc7.png)

Do I have to unpack this manually? Thank you!

For anyone who wants to look at the exe (no other game files will be provided, **only the exe**) you can download it here: https://pixeldrain.com/u/ETLbmLV6

**Comment by atom0s** [comment]
This file is not protected with SteamStub.

The name you are seeing in those tools can be a little misleading in regards to being SteamStub or not. But it is not. Instead, that 'Stub: Valve' is referring to what kind of DOS stub is present in the PE file. Generally, most 32bit/64bit files include a generic 16bit DOS stub which will just print the following message to the console when trying to be ran:

```
This program cannot be run in MS-DOS mode.
```

Valve replaces the DOS stub in files with its own unique stub for each executable file that it can properly adjust for. Their replacement stub has several purposes but that is outside of the scope of this project.
