### ISSUE TITLE
Error: Data Table Not Found 

### ISSUE THREAD

**Issue by adren0chrom3** [atom0s/Steamless#98]
I'm trying to download Lobotomy Corporation at the moment, and after I put it through Steamless and try to launch it with SmartSteamEmu, it always gives me an error. It says, "There should be 'LobotomyCorp.exe_Data' folder next to the executable." I've consulted a few online forms, and they all just recommend renaming the exe file from "LobotomyCorp" to "LobotomyCorp.exe." Unfortunately, I still get the same result of the appliance asking for a data folder. 

Thank you for your time! big fan, atom0s
![aa](https://user-images.githubusercontent.com/130555194/231427649-8842f96f-5373-4f5a-b0ec-bd83e9af36ef.png)

**Comment by atom0s** [comment]
Given that the executable is running properly but erroring later, it means that Steamless did its job in removing the SteamStub layer. Further errors/crashes/issues are not something I help with such as this as it is not in the scope of Steamless.

As a quick suggestion though, if you are running the unpacked exe, make sure it is in the same folder as the original was located. It is also recommended that you backup the original exe, rename it to something else and rename the unpacked exe to the original real file name in case the game is coded to look for the same name as the exe when loading data.
